>png("/Users/.../plot4.png")
> par(mfrow=c(2,2), mar=c(4,4,2,1))
> plot(power$Time3, power$Global_active_power, type="l", xlab="", ylab="Global Active Power")
> plot(power$Time3, power$Voltage, type="l", xlab="datetime", ylab="Voltage")
> with(power, plot(Time3, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
> lines(power$Time3, power$Sub_metering_2, type="l", col="Red")
> lines(power$Time3, power$Sub_metering_3, type="l", col="Blue")
> legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("Black", "Red", "Blue"))
> plot(power$Time3, power$Global_reactive_power, type="l", xlab="datetime", ylab="Global Reactive Power")
> dev.off()
